import os
import pathlib

SAMPLES_DIRECTORY = pathlib.Path(os.path.expanduser('~/.ros2/easy_handeye2/samples'))
CALIBRATIONS_DIRECTORY = pathlib.Path(os.path.expanduser('~/.ros2/easy_handeye2/calibrations'))

# CALIBRATION_NAMESPACE = ''
CALIBRATION_NAMESPACE = '/easy_handeye2/calibration/'

LIST_ALGORITHMS_TOPIC = CALIBRATION_NAMESPACE + 'list_algorithms'
SET_ALGORITHM_TOPIC = CALIBRATION_NAMESPACE + 'set_algorithm'
GET_CURRENT_TRANSFORMS_TOPIC = CALIBRATION_NAMESPACE + 'get_current_transforms'
GET_SAMPLE_LIST_TOPIC = CALIBRATION_NAMESPACE + 'get_sample_list'
TAKE_SAMPLE_TOPIC = CALIBRATION_NAMESPACE + 'take_sample'
REMOVE_SAMPLE_TOPIC = CALIBRATION_NAMESPACE + 'remove_sample'
SAVE_SAMPLES_TOPIC = CALIBRATION_NAMESPACE + 'save_samples'
LOAD_SAMPLES_TOPIC = CALIBRATION_NAMESPACE + 'load_samples'
COMPUTE_CALIBRATION_TOPIC = CALIBRATION_NAMESPACE + 'compute_calibration'
SAVE_CALIBRATION_TOPIC = CALIBRATION_NAMESPACE + 'save_calibration'

CHECK_STARTING_POSE_TOPIC = CALIBRATION_NAMESPACE + 'check_starting_pose'
ENUMERATE_TARGET_POSES_TOPIC = CALIBRATION_NAMESPACE + 'enumerate_target_poses'
SELECT_TARGET_POSE_TOPIC = CALIBRATION_NAMESPACE + 'select_target_pose'
PLAN_TO_SELECTED_TARGET_POSE_TOPIC = CALIBRATION_NAMESPACE + 'plan_to_selected_target_pose'
EXECUTE_PLAN_TOPIC = CALIBRATION_NAMESPACE + 'execute_plan'
